# Generated by Django 3.2.5 on 2021-07-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_price_discrount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_discrount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
