# Generated by Django 3.2.5 on 2021-07-31 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price_discrount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_discrount',
            new_name='price_discount',
        ),
    ]
